package rta.service;

import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;
import rta.entity.BankSummaryReport;

import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class ReportPdfService {

    private static final DeviceRgb HEADER_BG = new DeviceRgb(59, 130, 246);
    private static final DeviceRgb LIGHT_BG = new DeviceRgb(241, 245, 249);
    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public byte[] generateReportPdf(BankSummaryReport report) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfDocument pdfDoc = new PdfDocument(new PdfWriter(baos));
        Document doc = new Document(pdfDoc);

        // Title
        doc.add(new Paragraph("Bank Summary Report")
                .setFontSize(22)
                .setBold()
                .setFontColor(new DeviceRgb(30, 41, 59))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(5));

        doc.add(new Paragraph("Report ID: " + report.getId())
                .setFontSize(10)
                .setFontColor(new DeviceRgb(148, 163, 184))
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20));

        // Details table
        Table table = new Table(UnitValue.createPercentArray(new float[]{35, 65}))
                .useAllAvailableWidth()
                .setMarginBottom(20);

        addRow(table, "Merchant ID", report.getMerchantId());
        addRow(table, "File Name", report.getFileName());
        addRow(table, "Original File Name", valOrNa(report.getOriginalFileName()));
        addRow(table, "Batch ID", report.getBatchId() != null ? report.getBatchId().toString() : "N/A");
        addRow(table, "Bank Status", report.getBankStatus());
        addRow(table, "Bank Reference", valOrNa(report.getBankReference()));

        doc.add(table);

        // Transaction summary
        doc.add(new Paragraph("Transaction Summary")
                .setFontSize(16)
                .setBold()
                .setFontColor(new DeviceRgb(30, 41, 59))
                .setMarginBottom(10));

        Table txnTable = new Table(UnitValue.createPercentArray(new float[]{25, 25, 25, 25}))
                .useAllAvailableWidth()
                .setMarginBottom(20);

        // Header row
        addHeaderCell(txnTable, "Total Txn");
        addHeaderCell(txnTable, "Successful");
        addHeaderCell(txnTable, "Failed");
        addHeaderCell(txnTable, "Total Amount");

        // Data row
        txnTable.addCell(dataCell(intOrNa(report.getTotalTransactions())));
        txnTable.addCell(dataCell(intOrNa(report.getSuccessfulTransactions()))
                .setFontColor(new DeviceRgb(22, 163, 74)));
        txnTable.addCell(dataCell(intOrNa(report.getFailedTransactions()))
                .setFontColor(new DeviceRgb(220, 38, 38)));
        txnTable.addCell(dataCell(
                report.getTotalAmount() != null
                ? String.format("%.2f %s", report.getTotalAmount(), valOrEmpty(report.getCurrency()))
                : "N/A"));

        doc.add(txnTable);

        // Timestamps
        Table timeTable = new Table(UnitValue.createPercentArray(new float[]{35, 65}))
                .useAllAvailableWidth()
                .setMarginBottom(20);

        addRow(timeTable, "Processed At",
                report.getProcessedAt() != null ? report.getProcessedAt().format(DATE_FMT) : "N/A");
        addRow(timeTable, "Received At",
                report.getReceivedAt() != null ? report.getReceivedAt().format(DATE_FMT) : "N/A");

        doc.add(timeTable);

        // Remarks
        if (report.getRemarks() != null && !report.getRemarks().isEmpty()) {
            doc.add(new Paragraph("Remarks")
                    .setFontSize(14)
                    .setBold()
                    .setMarginBottom(5));
            doc.add(new Paragraph(report.getRemarks())
                    .setFontSize(11)
                    .setFontColor(new DeviceRgb(71, 85, 105))
                    .setMarginBottom(20));
        }

        // Footer
        doc.add(new Paragraph("Generated by RTA Merchant Upload System")
                .setFontSize(9)
                .setFontColor(new DeviceRgb(148, 163, 184))
                .setTextAlignment(TextAlignment.CENTER));

        doc.close();
        return baos.toByteArray();
    }

    private void addRow(Table table, String label, String value) {
        table.addCell(new Cell()
                .add(new Paragraph(label).setBold().setFontSize(11))
                .setBackgroundColor(LIGHT_BG)
                .setPadding(8));
        table.addCell(new Cell()
                .add(new Paragraph(value).setFontSize(11))
                .setPadding(8));
    }

    private void addHeaderCell(Table table, String text) {
        table.addHeaderCell(new Cell()
                .add(new Paragraph(text).setBold().setFontSize(11).setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(HEADER_BG)
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER));
    }

    private Cell dataCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setFontSize(12))
                .setPadding(8)
                .setTextAlignment(TextAlignment.CENTER);
    }

    private String valOrNa(String val) {
        return val != null && !val.isEmpty() ? val : "N/A";
    }

    private String valOrEmpty(String val) {
        return val != null ? val : "";
    }

    private String intOrNa(Integer val) {
        return val != null ? val.toString() : "N/A";
    }
}
